CREATE TABLE project_structure (
  project_structure_id INT NOT NULL AUTO_INCREMENT COMMENT 'Autogenerated numeric ID that is unique',
  project_structure_html LONGTEXT NOT NULL COMMENT 'HTML string of project structure data',
  last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp for last cache refresh of project structure data',
  PRIMARY KEY (project_structure_id))
